### ISSUE TITLE
Extend proxy switching to npm, github?

### ISSUE THREAD

**Issue by rlasjunies** [satokaz/vscode-toggleProxy#2]
Hi @satokaz ,

 I am happy you have accepted the proposal.

 In fact my "proxy issue" is wider than just 'vscode'. My issue is also related to 'npm' and 'github'. Every time I change work place, I've to switch proxy settings in '.npmrc' and  '.gitconfig' located in the windows user folder (I do not use linux). 

 Do you have the same issue? Do you have a magic solution to "easily" switch the proxy mode of npm and git?

 What about doing it via 'vscode-toggleProxy'? Can be an interesting exercise, we may work on it together if you are interested ;-)

**Comment by satokaz** [comment]
Hi @rlasjunies ,

Yes, I have the same suffering.
I'm using a macOS (Almost no use Windows.).
I am running the following script every time the environment (home, office, etc...) changes.

``` bash
#!/bin/bash
/sbin/ping -c 1 -W 500 $1 >> /dev/null

if test $? -eq 0; then
   echo "Set global http.proxy=http://$1:$2"
   echo "Set global https.proxy=http://$1:$2"
   git config --global http.proxy "http://$1:$2"
   git config --global https.proxy "http://$1:$2"
   # npm
   npm -g config set proxy "http://$1:$2"
   npm -g config set https-proxy "http://$1:$2" 
else
   echo 'Unset global http.proxy'
   echo 'Unset global https.proxy'
   git config --global http.proxy ''
   git config --global https.proxy ''
   # npm
   npm -g config delete proxy
   npm -g config delete https-proxy
fi 
```

Pass the proxy server name and port number to the argument.
- Ping the proxy server of the argument
- Set the proxy server name of the argument if there is a reply
- Unset the proxy if there is no reply

``` bash
$ proxy_update.sh proxy.sample.com 80
```

typings is not implemented yet because the need to edit environment variable or configuration file.

I wonder if such an operation should I Come to implement the extension?

**Comment by rlasjunies** [comment]
hi @satokaz ,

So we have the same impediment. 

I do not understand your comment: `I wonder if such an operation should I Come to implement the extension?`

Are you interested to implement it? or you have some doubt to implement proxy switch of npm, git, ... in vscode extension?

I've some doubt today to implement it in vscode extension. But if you are interested we may work together. If you not interested, we close the discussion and we continue to switch "manually" the proxy of the dev. tools.

**Comment by satokaz** [comment]
hi @rlasjunies ,

I'm sorry for the late reply.
I thought, but I still thought that should not be implemented in extensions.

Various tools such as git/npm/typings/gulp/request nodemodule/etc... require proxy connection.
And each tool has different setting.

My conclusions:

- VS Code uses vscode-toggleproxy extension
- Other tools (git/npm/typings/gulp/request nodemodule/etc...)  use the http_proxy and https_proxy environment variable.Fortunately, it is made to refer to the environment variable http_proxy and https_proxy.

It is difficult in various ways...
For the http_proxy environment variable, I would like to add it as a tips to the extensions README.md.

Thank you for giving us the opportunity to think.

**Comment by rlasjunies** [comment]
hi @satokaz,

fine for me, you may close the issue for now. 

best regards
